apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  annotations:
    kubernetes.io/change-cause: "Initial deployment of the app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      name: product-service-k8s
      labels:
        env: prod
        app: product-service
        app.kubernetes.io/name: product-service
    spec:
      containers:
        - name: product-service
          image: dentabramasta/product-service:v1
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app.kubernetes.io/name: product-service
  ports:
    - name: product-service-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27020
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27020
      targetPort: 27020

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazingateaway
  annotations:
    kubernetes.io/change-cause: "Initial deployment of the app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazingateaway
  template:
    metadata:
      labels:
        app: amazingateaway
    spec:
      containers:
        - name: amazingateaway
          image: dentabramasta/amazingateaway:v1
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: amazingateaway
spec:
  selector:
    app: amazingateaway
  ports:
    - name: http-web-api
      protocol: TCP
      port: 8001
      targetPort: 8080
