apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazingateaway
  annotations:
    kubernetes.io/change-cause: "Initional deployment of the app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazingateaway
  template:
    metadata:
      name: amazingateaway-k8s
      labels:
        env: prod
        app: amazingateaway
        app.kubernetes.io/name: amazingateaway
    spec:
      containers:
        - name: product-service
          image: dentabramasta/amazingateaway:v1
          ports:
            - containerPort: 80
              name: http-web-api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: amazingateaway
spec:
  selector:
    app.kubernetes.io/name: amazingateaway
  ports:
    - name: amazingateaway-port
      protocol: TCP
      port: 8005
      targetPort: 80
  type: LoadBalancer
