name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-product-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.0
          buildkitd-flags: --debug

      - name: Build Product Service Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:${{ github.sha }} ./Product-Service
          echo "Product Service Docker image tag: ${{ secrets.DOCKER_USERNAME }}/product-service:${{ github.sha }}"

  build-api-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build API Gateway Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/amazingateaway:${{ github.sha }} ./AmazinGateaway
          echo "Product Service Docker image tag: ${{ secrets.DOCKER_USERNAME }}/amazingateaway:${{ github.sha }}"

  deploy-product-service:
    needs: build-product-service
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Product Service Docker image
        env:
          APP_UID: 1000 # Provide appropriate user ID
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service:${{ github.sha }}
  
  deploy-api-gateway:
    needs: build-api-gateway
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API Gateway Docker image
        env:
          APP_UID: 1000 # Provide appropriate user ID
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/amazingateaway:${{ github.sha }}
