name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Product Service Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:${{ github.sha }} ./Product-Service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/amazingateaway:${{ github.sha }} ./AmazinGateaway

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Product Service Docker image
        env:
          APP_UID: 1000 # Provide appropriate user ID
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin <<< ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service:${{ github.sha }}

      - name: Deploy API Gateway Docker image
        env:
          APP_UID: 1000 # Provide appropriate user ID
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin <<< ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/amazingateaway:${{ github.sha }}
