name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-product-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Product Build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/product-service
          tags: ${{ github.sha }}
          dockerfiles: |
            ./Product-Service

  build-api-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build API Gateway Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/amazingateaway:${{ github.sha }} ./AmazinGateaway
          docker image ls

  deploy-product-service:
    name: push image to docker.io
    uses: redhat-actions/push-to-registry@v2
    with:
      image: ${{ steps.Product-Build.outputs.image }}
      tags: ${{ steps.Product-Build.outputs.tags }}
      registry: docker.io
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
  
  deploy-api-gateway:
    needs: build-api-gateway
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API Gateway Docker image
        env:
          APP_UID: 1000 # Provide appropriate user ID
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin <<< ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/amazingateaway:${{ github.sha }}
